sudo: required

env:
  - TEST_SERVER=tomcat
  - TEST_SERVER=websphere-liberty
  - TEST_SERVER=jetty
  - TEST_SERVER=wildfly

services: docker

language: java

jdk: oraclejdk8

cache:
  directories: $HOME/.m2/repository

install: echo "<settings><servers><server><id>bintray</id><username>\${env.BINTRAY_USER}</username><password>\${env.BINTRAY_KEY}</password></server></servers></settings>" > ~/.m2/settings.xml

script: mvn clean install -Denv=$TEST_SERVER -U -Psnapshots

after_success: if [[ $TRAVIS_PULL_REQUEST = false ]] && [[ $TRAVIS_BRANCH = master ]]; then chmod +x deploy_ghpages.sh && ./deploy_ghpages.sh; fi
